services:
  achievement-tracker:
    container_name: achievement-tracker
    build:
      context: .
    env_file:
      - .env
    networks:
      - container-dmz
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.achievements.rule=Host(`achievements.roymond.net`)"
      - "traefik.http.routers.achievements.entrypoints=websecure"
      - "traefik.http.routers.achievements.tls.certresolver=production"
      - "traefik.http.services.achievements.loadbalancer.server.port=5555"
    ports:
      - "5555:5555"
    volumes:
      - ./src:/src
      - ./public:/public
    restart: always

networks:
  container-dmz:
    external: true
